name: Docker Image CI

on:
  push:
    branches: 
      - develop
      
  pull_request:
    branches: [ main ]

jobs:
    nginx_pla_dep_gui:
            name: nginx_pla_dep_gui    
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
