name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: nginx_PLA_DEP_GUI
      run: docker build . --file ../../dockers/Dockerfile --tag $name:$(date +%s)
